version: 0.1.1
default:
  POSTGRES_DBNAME: postgres
  POSTGRES_USER: demo_user
  POSTGRES_PASSWORD: make_data_magical
  POSTGRES_HOST: db.pcrjclqaoqibkbptixsw.supabase.co
  POSTGRES_PORT: 5432
  POSTGRES_SCHEMA: elt_demo
